return {
    mod_name = { en = "Darktide Network Monitor" },
    mod_description = { en = "Shows live ping, stability, session statistics, server region, and optional advanced connection data." },
    hud_ping = { en = "PING %s" },
    hud_average = { en = "AVG PING %s" },
    hud_jitter = { en = "JITTER %s" },
    hud_minimum = { en = "MIN %s" },
    hud_maximum = { en = "MAX %s" },
    hud_tick_rate = { en = "TICKRATE %d HZ" },
    hud_send_buffer = { en = "SEND BUF %.0f KB" },
    hud_tick_rate_measuring = { en = "TICKRATE ..." },
    hud_send_buffer_measuring = { en = "SEND BUF ..." },
    milliseconds = { en = "%d ms" },
    measuring = { en = "..." },
    hud_endpoint = { en = "ENDPOINT %s  |  REGION %s" },
    hud_endpoint_accelerated = { en = "ENDPOINT %s  |  REGION %s  |  ACCELERATED" },
    hud_endpoint_only = { en = "ENDPOINT %s" },
    hud_endpoint_only_accelerated = { en = "ENDPOINT %s  |  ACCELERATED" },
    hud_region_only = { en = "REGION %s" },
    unavailable = { en = "unavailable" },
    unknown = { en = "unknown" },
    show_only_with_tactical_overlay = { en = "Only show with Tactical Overlay" },
    show_only_with_tactical_overlay_tooltip = { en = "Only displays the monitor while the Tactical Overlay key is held (Tab by default)." },
    ui_group = { en = "UI Settings" },
    ui_group_tooltip = { en = "Adjust the monitor's appearance and position." },
    statistics_group = { en = "Statistics" },
    statistics_group_tooltip = { en = "Choose which connection statistics are shown in the HUD." },
    show_ping = { en = "Show ping" },
    show_ping_tooltip = { en = "Shows the latest round-trip time between you and the server. Lower is better." },
    show_average = { en = "Show average ping" },
    show_average_tooltip = { en = "Shows your average ping since entering the current mission or Mourningstar session." },
    show_jitter = { en = "Show jitter" },
    show_jitter_tooltip = { en = "Shows how much your ping varies over roughly 30 seconds. Lower means a more stable connection." },
    show_minimum = { en = "Show minimum ping" },
    show_minimum_tooltip = { en = "Shows the lowest ping measured during the current session." },
    show_maximum = { en = "Show maximum ping" },
    show_maximum_tooltip = { en = "Shows the highest ping measured during the current session." },
    show_tick_rate = { en = "Show server tickrate" },
    show_tick_rate_tooltip = { en = "Shows how many simulation updates per second the server connection is configured to use. This does not measure whether the server keeps up." },
    show_send_buffer = { en = "Show send buffer" },
    show_send_buffer_tooltip = { en = "Shows free space for reliable messages sent to the server. Very low space can mean messages are queuing; Darktide delays some sends below 8 KB." },
    show_endpoint = { en = "Show endpoint IP" },
    show_endpoint_tooltip = { en = "Shows the address Darktide connects to. It may be an accelerated routing endpoint rather than the physical game server." },
    show_region = { en = "Show region" },
    show_region_tooltip = { en = "Shows the server region reported by the current connection." },
    show_accent_line = { en = "Show accent line" },
    show_accent_line_tooltip = { en = "Shows the thin colored line above the connection values." },
    x_offset = { en = "Horizontal offset" },
    x_offset_tooltip = { en = "Moves the HUD horizontally. Positive values move it right." },
    y_offset = { en = "Vertical offset" },
    y_offset_tooltip = { en = "Moves the HUD vertically. Positive values move it up." },
}
